on:
  push:
    tags:
      - '*'

name: Create release

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set package scope
        run: |
          sed -i "s|danskernesdigitalebibliotek/ddb-react|${GITHUB_REPOSITORY}|g" package.json
          cat package.json
      - name: Set package version
        run: yarn version --new-version ${GITHUB_REF:10} --no-git-tag-version
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Build project
        run: |
          VERSION_FILE_NAME=$GITHUB_REPOSITORY \
          VERSION_FILE_VERSION=${GITHUB_REF:10} \
          yarn build
      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .
            !node_modules

  github_release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Zip build
        run: |
          zip -r -j dist.zip dist/
      - name: Install GHR
        run: |
          curl --fail --silent --location --output ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar -zxf ghr.tar.gz
          echo "./ghr_v0.13.0_linux_amd64" >> $GITHUB_PATH
      - name: Create release with asset
        run: |
          ghr -replace -delete -n ${GITHUB_REF:10} -c $GITHUB_SHA ${GITHUB_REF:10} dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  github_npm_package:
    name: Publish GitHub NPM package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish NPM package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
